name: snake
on:
  schedule:
    - cron: '*/5 * * * *'  
  push:
    branches:
      - main
jobs:
  game:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Play Snake Game
        uses: Platane/snk@master
        with:
          github_user: 'gggggeric' 
          image: true  
